# Site Settings
baseurl: ""
url : "https://tanzng.github.io"

# Blog Settings
theme_settings :
  title : tan(x)
  favicon : assets/favicon.ico
  blog : "> tan(x) blog "

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Tania R. Zúñiga
    description : Computer Engineering student at Universidad Autónoma Metropolitana.
    experience :
      - start : 2020-05-04
        end : Until now
        experience : UAM, PAEA Facilitator
    skills : 
      - skill : Python
        value : 60  # Percent value
      - skill : C++
        value : 50  # Percent value      
        
  # Icons
  icons :
    email: tania@tanx.dev  # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/tania-r-zuniga/ # Full URL 
    github: TanZng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: https://twitter.com/tanx_dev
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : https-tanzng-github-io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
