# Site Settings
baseurl: ""
url : "https://tanzng.github.io"
disqus_shortname : 'https-tanzng-github-io'
comments: true

# Blog Settings
theme_settings :
  title : tan(x) blog
  favicon : assets/python.ico
  comments : True
  disqus_shortname : 'https-tanzng-github-io'

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Tania R. Zúñiga
    description : Computer Engineering student at Universidad Autónoma Metropolitana.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Python & C++
        value : 70  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/tania-r-z%C3%BA%C3%B1iga-b0a969158/ # Full URL 
    github: TanZng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
